version: '3.8'

services:
  # Разработка
  dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BASE_PATH=/
      # Для локальной разработки используем переменные из файла .env
      # Если они не будут настроены, форма будет работать только локально с .env файлом

  # Production локально
  prod:
    build:
      context: .
      target: production
      args:
        BASE_PATH: /
        # Для локальной сборки указываем эти значения в .env.local или передаем при запуске
        EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
        EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
        EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
    ports:
      - "8080:80"

  # GitHub Pages симуляция
  github:
    build:
      context: .
      target: production
      args:
        BASE_PATH: /web_studio/
        # Для локальной сборки указываем эти значения в .env.local или передаем при запуске
        EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
        EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
        EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
    ports:
      - "8081:80"

  # Production с вашим Docker Hub репозиторием
  production:
    image: elenasoshina/web_studio:latest
    build:
      context: .
      target: production
      args:
        BASE_PATH: /
        EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
        EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
        EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
    ports:
      - "80:80"
    restart: unless-stopped
